### ISSUE TITLE
Mimic sites placement procedure / adjustments for new robot

### ISSUE THREAD

**Issue by alik-git** [robfiras/loco-mujoco#59]
Hi @robfiras 

Thank you for this awesome open source project!

I am currently working with k-scale lab's kbot humanoid and loco-mujoco to experiment with imitation learning baselines like amp, which has been super fun.

However, when replaying samples from the AMASS dataset, the motion often does not look quite right. I believe this is because I have not set up the mimic sites correctly for kbot's xml. I was wondering:

**What's the procedure for correctly setting up the mimic sites? Do I need to match their orientation as well, or just position? Is there a way to verify that I have set them up correctly / optimally?**

All the code I am working with is in [this fork](https://github.com/kscalelabs/loco-mujoco) of your repo. You can see the comparison to your master branch here: https://github.com/robfiras/loco-mujoco/compare/master...kscalelabs:loco-mujoco:master
There are basically no changes other than adding the Kbot environment.

Here is how I have currently set up the sites for kbot:

<img src="https://github.com/user-attachments/assets/3ef85b37-95ab-4eea-8600-9507a40407cc" alt="KBot Sites Overview" width="200"/>

Just the sites here
<img src="https://github.com/user-attachments/assets/402d7b64-cb2f-4ef4-a14d-a09c12eac497" alt="KBot Sites Only" width="200"/>

And here is what the kbot looks like when I run the `smpl_example.py` script with the `ACCAD/ACCAD/Male2General_c3d/male2 Calibration_poses` data sample. You can see that the left foot is not straight / correct.

https://github.com/user-attachments/assets/264b4d05-ad42-4de1-b3ae-2b66ee32bbd7

 This is more clear when replaying a dancing data sample, here you can see the mismatch causes the left foot to be backwards. The sample is `DanceDB/DanceDB/20120911_TheodorosSourmelis/Capoeira_Theodoros_v2_C3D_poses`

https://github.com/user-attachments/assets/1b3c48c5-d28b-41ff-a132-a3c489a967fe

For comparison, you can also see that the Unitree H1 does not have the this problem.

https://github.com/user-attachments/assets/0925ba81-f4eb-4830-97c1-20b44dd7e50e

I would very much appreciate some guidance on how I can go about fixing the mimic site placement. Thank you in advance for your help!

**Comment by robfiras** [comment]
Hi @alik-git,
super cool that you managed to add your robot so quickly! Would love to see it fully supported in locomujoco soon!

I think the reason for the weird behavior is that the optimization is getting stuck in local optima due to collisions and joint limits. I played around with your config and i think I managed to get better results:

https://github.com/user-attachments/assets/cf617508-e569-4630-b4dd-a86433191b34

This is the new config:
```
# Inherits from defaults.yaml

# Define reusable variables/defaults
default_constraint_type: &weld_constraint mjEQ_WELD # Define the anchor here
default_torque_scale: &default_torque 1.0 # Define the torque anchor here

# Map mimic sites from kbot_v2.xml to SMPL joint names
site_joint_matches:
  pelvis_mimic:
    smpl_joint: Pelvis
    equality_constraint_type: *weld_constraint # Use alias
    torque_scale: *default_torque # Use alias
  upper_body_mimic:
    smpl_joint: Chest
    equality_constraint_type: *weld_constraint # Use alias
    torque_scale: *default_torque # Use alias
  head_mimic:
    smpl_joint: Head
    equality_constraint_type: *weld_constraint # Use alias
    torque_scale: *default_torque # Use alias
  left_shoulder_mimic:
    smpl_joint: L_Shoulder
    equality_constraint_type: *weld_constraint # Use alias
    torque_scale: *default_torque # Use alias
  left_elbow_mimic:
    smpl_joint: L_Elbow
    equality_constraint_type: *weld_constraint # Use alias
    torque_scale: *default_torque # Use alias
  left_wrist_mimic:
    smpl_joint: L_Wrist
    equality_constraint_type: *weld_constraint # Use alias
    torque_scale: *default_torque # Use alias
  left_hip_mimic:
    smpl_joint: L_Hip
    equality_constraint_type: *weld_constraint # Use alias
    torque_scale: *default_torque # Use alias
  left_knee_mimic:
    smpl_joint: L_Knee
    equality_constraint_type: *weld_constraint # Use alias
    torque_scale: 10 # Use alias
  left_foot_mimic:
    smpl_joint: L_Ankle
    equality_constraint_type: *weld_constraint # Use alias
    torque_scale: 10 # Use alias
  right_shoulder_mimic:
    smpl_joint: R_Shoulder
    equality_constraint_type: *weld_constraint # Use alias
    torque_scale: *default_torque # Use alias
  right_elbow_mimic:
    smpl_joint: R_Elbow
    equality_constraint_type: *weld_constraint # Use alias
    torque_scale: *default_torque # Use alias
  right_wrist_mimic:
    smpl_joint: R_Wrist
    equality_constraint_type: *weld_constraint # Use alias
    torque_scale: *default_torque # Use alias
  right_hip_mimic:
    smpl_joint: R_Hip
    equality_constraint_type: *weld_constraint # Use alias
    torque_scale: *default_torque # Use alias
  right_knee_mimic:
    smpl_joint: R_Knee
    equality_constraint_type: *weld_constraint # Use alias
    torque_scale: 10 # Use alias
  right_foot_mimic:
    smpl_joint: R_Ankle
    equality_constraint_type: *weld_constraint # Use alias
    torque_scale: 10 # Use alias

robot_pose_modifier:
  - dof_left_shoulder_roll_03: "np.pi/2"
  # - dof_left_elbow_02: "np.pi/2"
  - dof_right_shoulder_roll_03: "-np.pi/2"
  # - dof_right_elbow_02: "np.pi/2"

optimization_params:
  z_offset_feet: -0.0
  disable_collision: true
  # disable_joint_limits_on_initialization: False


env_params: {}

```

fyi, the torque scale parameter tells how much importance should be given during optimization to orientation vs position matching. 0 -> only position matching, and the bigger the torquescale parameter becomes the more importance will be given to the orientation. From my experience, I can tell that it is more likely that the optimization will get stuck in local optimas if too much focus is given to the position. So raising that paramter for the problematic joints often resolves this issue
